"""The module provides typing for semi-internal database models/methods"""

from typing import Any, Self, TypeVar

M = TypeVar("M")

class DBWRapper:
    def commit(self): ...
    def rollback(self): ...

db: DBWRapper

class DBQuery[M]:
    def all(self) -> list[M]: ...
    def one(self) -> M: ...
    def one_or_none(self) -> M | None: ...
    def first(self) -> M: ...
    def last(self) -> M: ...
    def count(self) -> int: ...
    def filter_by(**kwargs: Any) -> DBQuery[M]: ...
    def order_by(*args: Any) -> DBQuery[M]: ...

class ExtraModel:
    id: int

    @classmethod
    def create(cls, **kwargs: Any) -> Self: ...
    def delete(self) -> None: ...
    @classmethod
    def filter(cls, **kwargs) -> list[Self]: ...
    @classmethod
    def objects_get(cls, **kwargs: Any) -> Self: ...
    @classmethod
    def objects_exists(cls, **kwargs) -> bool: ...
    @classmethod
    def objects_create(cls, **kwargs) -> Self: ...
    @classmethod
    def objects_filter(cls, **kwargs: Any) -> DBQuery[Self]: ...
